
name: Just testing out the cron thing
on:
  schedule:
  - cron: '10 22 * * *'
jobs:
  mergeTest2Prod:
    runs-on: ubuntu-latest
    steps:
      - name: let everyone know we're running
        run: echo "Hey everyone! I ran!"
